language: node_js
node_js:
    - "8.11.1"
install:
    - npm install
env:
  global:
   - NODE_ENV=test

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - createdb --username=postgres book_a_meal
  - createuser --username=postgres root
  - psql -c "ALTER ROLE root WITH PASSWORD 'Skylinq24'";
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root"; 
  - sequelize db:migrate 

script:
    - npm test
 
after_success:
  - npm run coveralls