language: node_js
node_js:
    - "8.11.1"
install:
    - npm install

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE book_a_meal;' -U postgres
  - sequelize db:migrate 

script:
    - npm test
 
after_success:
  - npm run coveralls